s = {'LocalObservationDateTime': '2024-12-25T15:21:00+03:00',
     'EpochTime': 1735129260,
     'WeatherText': 'Cloudy',
     'WeatherIcon': 7,
     'HasPrecipitation': False,
     'PrecipitationType': None,
     'IsDayTime': True,
     'Temperature': {'Metric': {'Value': -1.1,
                                'Unit': 'C',
                                'UnitType': 17},
                     'Imperial': {'Value': 30.0,
                                  'Unit': 'F',
                                  'UnitType': 18}},
     'RealFeelTemperature': {'Metric': {'Value': -6.6,
                                        'Unit': 'C',
                                        'UnitType': 17,
                                        'Phrase': 'Very Cold'},
                             'Imperial': {'Value': 20.0,
                                          'Unit': 'F',
                                          'UnitType': 18,
                                          'Phrase': 'Very Cold'}},
     'RealFeelTemperatureShade': {'Metric': {'Value': -6.6,
                                             'Unit': 'C',
                                             'UnitType': 17,
                                             'Phrase': 'Very Cold'},
                                  'Imperial': {'Value': 20.0,
                                               'Unit': 'F',
                                               'UnitType': 18,
                                               'Phrase': 'Very Cold'}},
     'RelativeHumidity': 92,
     'IndoorRelativeHumidity': 37,
     'DewPoint': {'Metric': {'Value': -2.2,
                             'Unit': 'C',
                             'UnitType': 17},
                  'Imperial': {'Value': 28.0,
                               'Unit': 'F',
                               'UnitType': 18}},
     'Wind': {'Direction': {'Degrees': 270,
                            'Localized': 'W',
                            'English': 'W'},
              'Speed': {'Metric': {'Value': 16.7,
                                   'Unit': 'km/h',
                                   'UnitType': 7},
                        'Imperial': {'Value': 10.4,
                                     'Unit': 'mi/h',
                                     'UnitType': 9}}},
     'WindGust': {'Speed': {'Metric': {'Value': 16.7,
                                       'Unit': 'km/h',
                                       'UnitType': 7},
                            'Imperial': {'Value': 10.4,
                                         'Unit': 'mi/h',
                                         'UnitType': 9}}},
     'UVIndex': 0,
     'UVIndexText': 'Low',
     'Visibility': {'Metric': {'Value': 16.1,
                               'Unit': 'km',
                               'UnitType': 6},
                    'Imperial': {'Value': 10.0,
                                 'Unit': 'mi',
                                 'UnitType': 2}},
     'ObstructionsToVisibility': '',
     'CloudCover': 100,
     'Ceiling': {'Metric': {'Value': 152.0,
                            'Unit': 'm',
                            'UnitType': 5},
                 'Imperial': {'Value': 500.0,
                              'Unit': 'ft',
                              'UnitType': 0}},
     'Pressure': {'Metric': {'Value': 1028.0,
                             'Unit': 'mb',
                             'UnitType': 14},
                  'Imperial': {'Value': 30.36,
                               'Unit': 'inHg',
                               'UnitType': 12}},
     'PressureTendency': {'LocalizedText': 'Steady',
                          'Code': 'S'},
     'Past24HourTemperatureDeparture': {'Metric': {'Value': -2.2,
                                                   'Unit': 'C',
                                                   'UnitType': 17},
                                        'Imperial': {'Value': -4.0,
                                                     'Unit': 'F',
                                                     'UnitType': 18}},
     'ApparentTemperature': {'Metric': {'Value': -1.1,
                                        'Unit': 'C',
                                        'UnitType': 17},
                             'Imperial': {'Value': 30.0,
                                          'Unit': 'F',
                                          'UnitType': 18}},
     'WindChillTemperature': {'Metric': {'Value': -6.1,
                                         'Unit': 'C',
                                         'UnitType': 17},
                              'Imperial': {'Value': 21.0,
                                           'Unit': 'F',
                                           'UnitType': 18}},
     'WetBulbTemperature': {'Metric': {'Value': -1.5,
                                       'Unit': 'C',
                                       'UnitType': 17},
                            'Imperial': {'Value': 29.0,
                                         'Unit': 'F',
                                         'UnitType': 18}},
     'WetBulbGlobeTemperature': {'Metric': {'Value': -1.1,
                                            'Unit': 'C',
                                            'UnitType': 17},
                                 'Imperial': {'Value': 30.0,
                                              'Unit': 'F',
                                              'UnitType': 18}},
     'Precip1hr': {'Metric': {'Value': 0.0,
                              'Unit': 'mm',
                              'UnitType': 3},
                   'Imperial': {'Value': 0.0,
                                'Unit': 'in',
                                'UnitType': 1}},
     'PrecipitationSummary': {'Precipitation': {'Metric': {'Value': 0.0,
                                                           'Unit': 'mm',
                                                           'UnitType': 3},
                                                'Imperial': {'Value': 0.0,
                                                             'Unit': 'in',
                                                             'UnitType': 1}},
                              'PastHour': {'Metric': {'Value': 0.0,
                                                      'Unit': 'mm',
                                                      'UnitType': 3},
                                           'Imperial': {'Value': 0.0,
                                                        'Unit': 'in',
                                                        'UnitType': 1}},
                              'Past3Hours': {'Metric': {'Value': 0.0,
                                                        'Unit': 'mm',
                                                        'UnitType': 3},
                                             'Imperial': {'Value': 0.0,
                                                          'Unit': 'in',
                                                          'UnitType': 1}},
                              'Past6Hours': {'Metric': {'Value': 0.0,
                                                        'Unit': 'mm',
                                                        'UnitType': 3},
                                             'Imperial': {'Value': 0.0,
                                                          'Unit': 'in',
                                                          'UnitType': 1}},
                              'Past9Hours': {'Metric': {'Value': 1.0,
                                                        'Unit': 'mm',
                                                        'UnitType': 3},
                                             'Imperial': {'Value': 0.04,
                                                          'Unit': 'in',
                                                          'UnitType': 1}},
                              'Past12Hours': {'Metric': {'Value': 3.0,
                                                         'Unit': 'mm',
                                                         'UnitType': 3},
                                              'Imperial': {'Value': 0.12,
                                                           'Unit': 'in',
                                                           'UnitType': 1}},
                              'Past18Hours': {'Metric': {'Value': 5.1,
                                                         'Unit': 'mm',
                                                         'UnitType': 3},
                                              'Imperial': {'Value': 0.2,
                                                           'Unit': 'in',
                                                           'UnitType': 1}},
                              'Past24Hours': {'Metric': {'Value': 7.5,
                                                         'Unit': 'mm',
                                                         'UnitType': 3},
                                              'Imperial': {'Value': 0.29,
                                                           'Unit': 'in',
                                                           'UnitType': 1}}},
     'TemperatureSummary': {'Past6HourRange': {'Minimum': {'Metric': {'Value': -2.8,
                                                                      'Unit': 'C',
                                                                      'UnitType': 17},
                                                           'Imperial': {'Value': 27.0,
                                                                        'Unit': 'F',
                                                                        'UnitType': 18}},
                                               'Maximum': {'Metric': {'Value': -1.1,
                                                                      'Unit': 'C',
                                                                      'UnitType': 17},
                                                           'Imperial': {'Value': 30.0,
                                                                        'Unit': 'F',
                                                                        'UnitType': 18}}},
                            'Past12HourRange': {'Minimum': {'Metric': {'Value': -2.8,
                                                                       'Unit': 'C',
                                                                       'UnitType': 17},
                                                            'Imperial': {'Value': 27.0,
                                                                         'Unit': 'F',
                                                                         'UnitType': 18}},
                                                'Maximum': {'Metric': {'Value': -1.1,
                                                                       'Unit': 'C',
                                                                       'UnitType': 17},
                                                            'Imperial': {'Value': 30.0,
                                                                         'Unit': 'F',
                                                                         'UnitType': 18}}},
                            'Past24HourRange': {'Minimum': {'Metric': {'Value': -2.8,
                                                                       'Unit': 'C',
                                                                       'UnitType': 17},
                                                            'Imperial': {'Value': 27.0,
                                                                         'Unit': 'F',
                                                                         'UnitType': 18}},
                                                'Maximum': {'Metric': {'Value': 1.1,
                                                                       'Unit': 'C',
                                                                       'UnitType': 17},
                                                            'Imperial': {'Value': 34.0,
                                                                         'Unit': 'F',
                                                                         'UnitType': 18}}}},
     'MobileLink': 'http://www.accuweather.com/en/ru/tverskoy/2515351/current-weather/2515351?lang=en-us',
     'Link': 'http://www.accuweather.com/en/ru/tverskoy/2515351/current-weather/2515351?lang=en-us'}
